# Este arquivo configura como a Netlify constrói e serve seu site.

# Seção de Build: Define os comandos para construir o projeto.
# A Netlify geralmente detecta isso automaticamente para projetos Vite, mas é bom ser explícito.
[build]
  command = "npm run build"
  publish = "dist"

# Seção de Redirecionamento: A chave para resolver nosso problema.
[[redirects]]
  # Para qualquer caminho solicitado...
  from = "/*"
  # ...sirva o arquivo index.html.
  to = "/index.html"
  # Com o status 200, que significa "OK" (não é um redirecionamento real, mas uma reescrita da URL).
  status = 200